# Generated by Django 2.1.2 on 2018-12-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='core.Meetup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('github_username', models.CharField(blank=True, max_length=64)),
                ('linkedin_url', models.URLField(blank=True)),
                ('slack_members_id', models.CharField(blank=True, max_length=64)),
                ('twitter_username', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('website_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Presenter'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='sponsor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Sponsor'),
        ),
    ]
