# Generated by Django 3.1.6 on 2021-02-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetups_to_edmonton_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
